{"errors":[{"instance":null,"message":"typname must be unique","origin":"DB","path":"typname","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":"enum_processos_status"},{"instance":null,"message":"typnamespace must be unique","origin":"DB","path":"typnamespace","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":"2200"}],"fields":{"typname":"enum_processos_status","typnamespace":"2200"},"level":"error","message":"Erro ao inicializar a aplicação: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"23505","constraint":"pg_type_typname_nsp_index","detail":"Key (typname, typnamespace)=(enum_processos_status, 2200) already exists.","file":"nbtinsert.c","length":425,"line":"666","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","severity":"ERROR","sql":"DROP TYPE IF EXISTS \"public\".\"enum_processos_status\"; DO 'BEGIN CREATE TYPE \"public\".\"enum_processos_status\" AS ENUM(''ativo'', ''arquivado'', ''suspenso''); EXCEPTION WHEN duplicate_object THEN null; END';","table":"pg_type","where":"SQL statement \"CREATE TYPE \"public\".\"enum_processos_status\" AS ENUM('ativo', 'arquivado', 'suspenso')\"\nPL/pgSQL function inline_code_block line 1 at SQL statement"},"parent":{"code":"23505","constraint":"pg_type_typname_nsp_index","detail":"Key (typname, typnamespace)=(enum_processos_status, 2200) already exists.","file":"nbtinsert.c","length":425,"line":"666","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","severity":"ERROR","sql":"DROP TYPE IF EXISTS \"public\".\"enum_processos_status\"; DO 'BEGIN CREATE TYPE \"public\".\"enum_processos_status\" AS ENUM(''ativo'', ''arquivado'', ''suspenso''); EXCEPTION WHEN duplicate_object THEN null; END';","table":"pg_type","where":"SQL statement \"CREATE TYPE \"public\".\"enum_processos_status\" AS ENUM('ativo', 'arquivado', 'suspenso')\"\nPL/pgSQL function inline_code_block line 1 at SQL statement"},"service":"acompanhamento-processual","sql":"DROP TYPE IF EXISTS \"public\".\"enum_processos_status\"; DO 'BEGIN CREATE TYPE \"public\".\"enum_processos_status\" AS ENUM(''ativo'', ''arquivado'', ''suspenso''); EXCEPTION WHEN duplicate_object THEN null; END';","stack":"Error\n    at Query.run (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/query-interface.js:117:76\n    at async PostgresQueryInterface.ensureEnums (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/query-interface.js:117:20)\n    at async PostgresQueryInterface.createTable (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:85:5)\n    at async Processo.sync (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/model.js:942:7)\n    at async Sequelize.sync (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:377:9)\n    at async initializeApp (file:///Users/mauriciooliveira/acompanhamento-processual/backend/src/app.js:135:5)\n    at async startServer (file:///Users/mauriciooliveira/acompanhamento-processual/backend/src/server.js:10:5)","timestamp":"2025-09-22T17:43:11.684Z"}
{"level":"error","message":"Erro ao inicializar a aplicação: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"acompanhamento-processual","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg-protocol/dist/parser.js:36:17)\n    at TLSSocket.<anonymous> (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg-protocol/dist/index.js:11:42)\n    at TLSSocket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-22T23:53:55.241Z"}
{"level":"error","message":"Erro ao inicializar a aplicação: column \"is_active\" does not exist","name":"SequelizeDatabaseError","original":{"code":"42703","file":"indexcmds.c","length":99,"line":"1888","name":"error","routine":"ComputeIndexAttrs","severity":"ERROR","sql":"CREATE INDEX \"push_subscriptions_is_active\" ON \"push_subscriptions\" (\"is_active\")"},"parameters":{},"parent":{"code":"42703","file":"indexcmds.c","length":99,"line":"1888","name":"error","routine":"ComputeIndexAttrs","severity":"ERROR","sql":"CREATE INDEX \"push_subscriptions_is_active\" ON \"push_subscriptions\" (\"is_active\")"},"service":"acompanhamento-processual","sql":"CREATE INDEX \"push_subscriptions_is_active\" ON \"push_subscriptions\" (\"is_active\")","stack":"Error\n    at Query.run (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.addIndex (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:250:12)\n    at async PushSubscription.sync (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/model.js:999:7)\n    at async Sequelize.sync (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:377:9)\n    at async initializeApp (file:///Users/mauriciooliveira/acompanhamento-processual/backend/src/app.js:135:5)\n    at async startServer (file:///Users/mauriciooliveira/acompanhamento-processual/backend/src/server.js:10:5)","timestamp":"2025-09-22T23:58:04.045Z"}
{"level":"error","message":"Erro ao inicializar a aplicação: column \"is_active\" does not exist","name":"SequelizeDatabaseError","original":{"code":"42703","file":"indexcmds.c","length":99,"line":"1888","name":"error","routine":"ComputeIndexAttrs","severity":"ERROR","sql":"CREATE INDEX \"push_subscriptions_is_active\" ON \"push_subscriptions\" (\"is_active\")"},"parameters":{},"parent":{"code":"42703","file":"indexcmds.c","length":99,"line":"1888","name":"error","routine":"ComputeIndexAttrs","severity":"ERROR","sql":"CREATE INDEX \"push_subscriptions_is_active\" ON \"push_subscriptions\" (\"is_active\")"},"service":"acompanhamento-processual","sql":"CREATE INDEX \"push_subscriptions_is_active\" ON \"push_subscriptions\" (\"is_active\")","stack":"Error\n    at Query.run (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.addIndex (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:250:12)\n    at async PushSubscription.sync (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/model.js:999:7)\n    at async Sequelize.sync (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:377:9)\n    at async initializeApp (file:///Users/mauriciooliveira/acompanhamento-processual/backend/src/app.js:135:5)\n    at async startServer (file:///Users/mauriciooliveira/acompanhamento-processual/backend/src/server.js:10:5)","timestamp":"2025-09-22T23:58:30.799Z"}
{"level":"error","message":"Erro ao inicializar a aplicação: ConnectionManager.getConnection was called after the connection manager was closed!","service":"acompanhamento-processual","stack":"Error: ConnectionManager.getConnection was called after the connection manager was closed!\n    at ConnectionManager.getConnection (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:70:13)\n    at /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:305:111\n    at /Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/retry-as-promised/dist/index.js:65:25\n    at new Promise (<anonymous>)\n    at retryAsPromised (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/retry-as-promised/dist/index.js:54:12)\n    at Sequelize.query (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:300:12)\n    at PostgresQueryInterface.dropTable (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:111:26)\n    at PostgresQueryInterface.dropTable (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/query-interface.js:151:17)\n    at Consulta.drop (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/model.js:1007:38)\n    at Sequelize.drop (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/sequelize.js:448:19)","timestamp":"2025-09-22T23:59:02.338Z"}
{"level":"error","message":"Erro ao inicializar a aplicação:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"acompanhamento-processual","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Socket.reportStreamError (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-24T17:49:15.538Z"}
{"level":"error","message":"Erro ao inicializar a aplicação:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"acompanhamento-processual","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Socket.reportStreamError (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-24T17:49:25.826Z"}
{"level":"error","message":"Erro ao inicializar a aplicação:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"acompanhamento-processual","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Socket.reportStreamError (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-25T00:02:42.356Z"}
{"level":"error","message":"Erro ao inicializar a aplicação:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"acompanhamento-processual","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Socket.reportStreamError (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-25T00:05:48.133Z"}
{"level":"error","message":"Erro ao inicializar a aplicação:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"acompanhamento-processual","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Socket.reportStreamError (/Users/mauriciooliveira/acompanhamento-processual/backend/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-25T00:15:48.499Z"}
